# Generated by Django 5.2.6 on 2025-09-03 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(db_column='T001IdAutor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T001Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='T001Apellido', max_length=100)),
                ('biografia', models.TextField(blank=True, db_column='T001Biografia', null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'T001Autor',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.AutoField(db_column='T002IdEditorial', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T002Nombre', max_length=150)),
                ('direccion', models.CharField(db_column='T002Direccion', max_length=255)),
                ('telefono', models.CharField(blank=True, db_column='T002Telefono', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'T002Editorial',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id_miembro', models.AutoField(db_column='T004IdMiembro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T004Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='T004Apellido', max_length=100)),
                ('email', models.EmailField(db_column='T004Email', max_length=254, unique=True)),
                ('fecha_membresia', models.DateField(db_column='T004FechaMembresia')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'T004Miembro',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(db_column='T003IdLibro', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='T003Titulo', max_length=200)),
                ('resumen', models.TextField(blank=True, db_column='T003Resumen', null=True)),
                ('isbn', models.CharField(db_column='T003ISBN', max_length=20, unique=True)),
                ('anio_publicacion', models.PositiveIntegerField(db_column='T003AnioPublicacion')),
                ('autor', models.ForeignKey(db_column='T003IdAutor', on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='api_app.autor')),
                ('editorial', models.ForeignKey(db_column='T003IdEditorial', on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='api_app.editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'T003Libro',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(db_column='T005IdPrestamo', primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(db_column='T005FechaPrestamo')),
                ('fecha_devolucion', models.DateField(blank=True, db_column='T005FechaDevolucion', null=True)),
                ('libro', models.ForeignKey(db_column='T005IdLibro', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='api_app.libro')),
                ('miembro', models.ForeignKey(db_column='T005IdMiembro', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='api_app.miembro')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'db_table': 'T005Prestamo',
            },
        ),
    ]
